CREATE TABLE t_user
(
  F_USER_ID      INT AUTO_INCREMENT
    PRIMARY KEY,
  F_ACCESS       VARCHAR(255) NULL,
  F_FIRST_NAME   VARCHAR(255) NULL,
  F_LAST_NAME    VARCHAR(255) NULL,
  F_MAIL         VARCHAR(255) NULL,
  F_MIDDLE_NAME  VARCHAR(255) NULL,
  F_PASSWORD     VARCHAR(255) NULL,
  F_PHONE_NUMBER VARCHAR(255) NULL,
  F_ROLE         VARCHAR(255) NULL,
  F_USERNAME     VARCHAR(255) NULL
);

CREATE TABLE t_address
(
  F_ADDRESS_ID INT AUTO_INCREMENT
    PRIMARY KEY,
  F_CITY       VARCHAR(255) NULL,
  F_FLAT       INT          NULL,
  F_HOUSE      VARCHAR(255) NULL,
  F_REGION     VARCHAR(255) NULL,
  F_STREET     VARCHAR(255) NULL,
  F_USER_ID    INT          NOT NULL
);
CREATE INDEX FKdsuv9yuqojl91rcjonr68oomb
  ON t_address (F_USER_ID);

CREATE TABLE t_feed_back
(
  F_FEED_BACK_ID INT AUTO_INCREMENT
    PRIMARY KEY,
  F_DATE         DATETIME     NULL,
  F_MAIL         VARCHAR(255) NULL,
  F_MESSAGE      LONGTEXT     NULL,
  F_TOPIC        VARCHAR(255) NULL,
  F_USER_NAME    VARCHAR(255) NULL,
  F_USER_ID      INT          NOT NULL
);
CREATE INDEX FK5ojkfsa44e89hfudhh2cvs5lu
  ON t_feed_back (F_USER_ID);

  CREATE TABLE t_goods
(
  F_GOODS_ID    INT AUTO_INCREMENT
    PRIMARY KEY,
  F_ARTICLE     VARCHAR(255)   NULL,
  F_CATEGORY    VARCHAR(255)   NULL,
  F_DESCRIPTION LONGTEXT       NULL,
  F_NAME        VARCHAR(255)   NULL,
  F_PRICE       DECIMAL(19, 2) NULL,
  F_USER_ID     INT            NOT NULL
);
CREATE INDEX FK7o4lwvsuv79b5ubc5bmv9lvo3
  ON t_goods (F_USER_ID);

  CREATE TABLE t_goods_file
(
  F_GOODS_ID  INT AUTO_INCREMENT
    PRIMARY KEY,
  F_FILE_NAME VARCHAR(255) NULL,
  F_LOCATION  VARCHAR(255) NULL
);

CREATE TABLE t_news
(
  F_NEWS_ID INT AUTO_INCREMENT
    PRIMARY KEY,
  F_CONTENT LONGTEXT     NULL,
  F_DATE    DATE         NULL,
  F_TITLE   VARCHAR(255) NULL,
  F_USER_ID INT          NOT NULL
);
CREATE INDEX FKiil6jqln7ebrkkytw8npk67nv
  ON t_news (F_USER_ID);

CREATE TABLE t_news_file
(
  F_NEWS_ID   INT AUTO_INCREMENT
    PRIMARY KEY,
  F_FILE_NAME VARCHAR(255) NULL,
  F_LOCATION  VARCHAR(255) NULL
);

CREATE TABLE t_basket
(
  F_BASKET_ID INT AUTO_INCREMENT
    PRIMARY KEY,
  F_QUANTITY  INT NULL,
  F_GOODS_ID  INT NULL,
  F_ORDER_ID  INT NULL,
  F_USER_ID   INT NOT NULL
);
CREATE INDEX FK2p1wnpb9t149w11mimlifqp2a
  ON t_basket (F_ORDER_ID);
CREATE INDEX FKby5b0m2a2vdjxu6fil1oob5i3
  ON t_basket (F_USER_ID);
CREATE INDEX FKkkcrbfwl3p0g6g3rcoyvkivmj
  ON t_basket (F_GOODS_ID);

  CREATE TABLE t_order
(
  F_ORDER_ID    INT AUTO_INCREMENT
    PRIMARY KEY,
  F_DATE        DATETIME       NULL,
  F_STATUS      VARCHAR(255)   NULL,
  F_TOTAL_PRICE DECIMAL(19, 2) NULL,
  F_USER_ID     INT            NOT NULL
);
CREATE INDEX FK9m8su6thy94ixb0sjt4hsijft
  ON t_order (F_USER_ID);

